export { Login, default as LoginPage } from './LoginPage'
export { SocialLogin, default as SocialLoginPage } from './SocialLoginPage'
//export * from './SocialLoginPage'
export * from './ForgotPasswordPage'
export * from './ResetPasswordPage'
